kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:8
  commands:
  - npm install
  # - npm rebuild node-sass
  - npm run-script build
# Package everything to dist folder
- name: dist
  image: debian
  commands:
  - ./dist.sh

trigger:
  branch:
  - master
