kind: pipeline
name: default

steps:
- name: build
  image: node:8
  commands:
  - npm install
  # - npm rebuild node-sass
  - npm run-script build
# Package everything to dist folder
- name: dist
  image: debian
  commands:
  - ./dist.sh

trigger:
  branch:
  - master

---
kind: pipeline
name: docker

steps:
- name: docker
  image: plugins/docker
  settings:
    # dry_run: true
    username: harvzor
    password:
      from_secret: docker_password
    repo: harvzor/custom-start-page
    tags: latest
